exec-once = hyprpaper
exec-once = sleep 1 && hyprctl hyprpaper preload "/home/anacanestraro/Imagens/wallpapers/wallpaper.jpg" && hyprctl hyprpaper wallpaper "eDP-1,/home/anacanestraro/Imagens/wallpapers/wallpaper.jpg"
