env = XCURSOR_THEME, Bibata-Modern-Ice
env = XCURSOR_SIZE, 24

monitor=,preferred,auto,1

$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun 

input {
	kb_layout = br
	kb_variant = abnt2
	follow_mouse = 1
	touchpad { 
		natural_scroll = true
	}
}

general {
	gaps_in = 6
	gaps_out = 12
	border_size = 2
	col.active_border= rgba(89b4faee) rgba(cba6f7ee) 45deg
	col.inactive_border = rgba(45475aaa)
	layout = dwindle
	resize_on_border = true
}

decoration {
	rounding = 12
	active_opacity = 1.0
	inactive_opacity = 0.92

	blur {
		enabled = true
		size = 6
		passes = 3
		new_optimizations = true
		ignore_opacity = true
	}

	shadow {
		enabled = true
		range = 20
		render_power = 3
		color = rgba(1a1a2eee)
	}
}

animations {
	enabled = true
	bezier = suave, 0.05, 0.9, 0.1, 1.0
	bezier = rapido, 0.15, 0.85, 0.25, 1.0

	animation = windows, 1, 5, suave, slide
	animation = windowsOut, 1, 5, suave, slide
	animation = border, 1, 8, default
	animation = borderangle, 1, 8, default
	animation = fade, 1, 6, suave
	animation = workspaces, 1, 5, rapido, slide
}


exec-once = waybar
exec-once = mako
exec-once = /usr/lib/polkit-kde-authentication-agent-1

bind = SUPER, Q, exec, $terminal
bind = SUPER, E, exec, $fileManager
bind = SUPER, R, exec, $menu
bind = SUPER, C, killactive
bind = SUPER, M, exit
bind = SUPER, V, togglefloating
bind = SUPER, F, fullscreen

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Redimensionar janela ativa
bind = SUPER CTRL, left, resizeactive, -60 0
bind = SUPER CTRL, right, resizeactive, 60 0
bind = SUPER CTRL, up, resizeactive, 0 -60
bind = SUPER CTRL, down, resizeactive, 0 60

# Mover janela de posição
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

# Energia e bloqueio
bind = SUPER, L, exec, hyprlock
bind = SUPER SHIFT, E, exec, systemctl poweroff
bind = SUPER SHIFT, R, exec, systemctl reboot
bind = SUPER SHIFT, S, exec, systemctl suspend

exec-once = awww-daemon
exec-once = sleep 1 && awww img "/home/anacanestraro/Imagens/wallpapers/wallpaper.jpg"
