background {
    monitor =
    path = /home/anacanestraro/Imagens/wallpapers/wallpaper.jpg
    blur_passes = 4
    blur_size = 10
    brightness = 0.4
    contrast = 0.9
}

# Relógio grande
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I:%M%p')"
    color = rgba(205, 214, 244, 0.95)
    font_size = 130
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 60
    halign = center
    valign = center
}

# Saudação
label {
    monitor =
    text = Oi, $USER
    color = rgba(205, 214, 244, 0.85)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, -80
    halign = center
    valign = center
}

# Campo de senha (cápsula translúcida)
input-field {
    monitor =
    size = 260, 50
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    inner_color = rgba(30, 30, 46, 0.6)
    font_color = rgba(205, 214, 244, 0.9)
    placeholder_text = <i>Input Password...</i>
    fade_on_empty = false
    rounding = 25
    position = 0, -140
    halign = center
    valign = center
}

# Rodapé
label {
    monitor =
    text = Indexical reminder of a morning well spent
    color = rgba(205, 214, 244, 0.7)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = bottom
}
